version: '3.8'

services:

  db:
    container_name: app-db
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: helloworld
      POSTGRES_DB: main
    ports:
      - "5432:5432"
    volumes:
      - $HOME/Desktop/PostgreSql-Snippets/infile:/infile
      - pg_data:/var/lib/postgresql/data/
      
volumes:
  pg_data:
